FROM eclipse-temurin:23-jdk AS build

RUN apt-get update && apt-get install -y ant

#Setgin working directory
WORKDIR /src

#Copyting everything to src
COPY . /src

WORKDIR /src/
RUN ant build-jar
RUN find /src

#Now for the runtime 
FROM eclipse-temurin:23-jre

#Setting a working directory in runtime stage

WORKDIR /app

#Copying from the build

COPY --from=build /src/build/jar/MainApp.jar /app/MainApp.jar

ENTRYPOINT [ "java","-jar","MainApp.jar" ]